// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZW0gfTHSIOIiOx2uivFgsnc1RnGEEEL4',
    appId: '1:802320830862:web:7beaa2bda8fe72d72b94df',
    messagingSenderId: '802320830862',
    projectId: 'evaluacion-fire-d9ab9',
    authDomain: 'evaluacion-fire-d9ab9.firebaseapp.com',
    databaseURL: 'https://evaluacion-fire-d9ab9-default-rtdb.firebaseio.com',
    storageBucket: 'evaluacion-fire-d9ab9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBArzbalc1zkkTYkeMrtFhyUMjHScJ-3BU',
    appId: '1:802320830862:android:a4506c349631e3ba2b94df',
    messagingSenderId: '802320830862',
    projectId: 'evaluacion-fire-d9ab9',
    databaseURL: 'https://evaluacion-fire-d9ab9-default-rtdb.firebaseio.com',
    storageBucket: 'evaluacion-fire-d9ab9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZW0gfTHSIOIiOx2uivFgsnc1RnGEEEL4',
    appId: '1:802320830862:web:360c4c182e8a75252b94df',
    messagingSenderId: '802320830862',
    projectId: 'evaluacion-fire-d9ab9',
    authDomain: 'evaluacion-fire-d9ab9.firebaseapp.com',
    databaseURL: 'https://evaluacion-fire-d9ab9-default-rtdb.firebaseio.com',
    storageBucket: 'evaluacion-fire-d9ab9.firebasestorage.app',
  );

}